# Generated by Django 5.2.9 on 2025-12-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('section', models.CharField(max_length=11)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
